modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="goilerweapony"
version="1.0.6"
displayName="Goilery Weapony"
logoFile="mod_icon.png"
credits="Thanks for the textures goes to nudlauflauch"
authors="Stehschnitzel"
description='''
This mod adds various weapons to se best game minecraft!
'''

[[dependencies.goilerweapony]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.goilerweapony]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.3]"
    ordering="NONE"
    side="BOTH"
